/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_managemeant_system3;
import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import org.apache.derby.iapi.sql.PreparedStatement;
/**
 *
 * @author Niwash Kumar
 */
public class PrintRecipt extends javax.swing.JFrame {

    /**
     * Creates new form PrintRecipt
     */
    public PrintRecipt() {
        initComponents();
        getRecord();
        Container c=getContentPane();
        c.setBackground(new Color(0,0,0));
    }
    
    public void getRecord(){
        try
        {
            java.sql.Connection con= DBConnection.getConnection();
            java.sql.PreparedStatement pst=con.prepareStatement("select * from fees_Details order by reciept_no desc limit 1");
             java.sql.ResultSet rs=pst.executeQuery();
             rs.next();
             txt_Receipt_no.setText(rs.getString("reciept_no"));
            txt_Payment_mode.setText(rs.getString("payment_mode"));
            String paymentMode=rs.getString("payment_mode");
            if(paymentMode.equalsIgnoreCase("cash")){
                lbl_cheque_Dd.setText("Cheque no");
                txt_Cheque_dd_no.setText("-");
                txt_bank_name.setText("-");
            }
            
             if(paymentMode.equalsIgnoreCase("cheque")){
                lbl_cheque_Dd.setText("Cheque no");
                txt_Cheque_dd_no.setText(rs.getString("cheque_no"));
                txt_bank_name.setText(rs.getString("Bank_name"));
            }
             
              if(paymentMode.equalsIgnoreCase("dd")){
                lbl_cheque_Dd.setText("DD no");
                txt_Cheque_dd_no.setText(rs.getString("dd_no"));
                txt_bank_name.setText(rs.getString("Bank_name"));
            }
               if(paymentMode.equalsIgnoreCase("Card")){
                lbl_cheque_Dd.setText("cheque no");
                txt_Cheque_dd_no.setText("-");
                txt_bank_name.setText(rs.getString("Bank_name"));
            }
            
            
            txt_Recieved_from.setText(rs.getString("student_name"));
            txt_Date.setText(rs.getString("date"));
             txt_GSTIN.setText(rs.getString("gstin"));
              txt_year1.setText(rs.getString("year1"));
              txt_year2.setText(rs.getString("year2"));
              txt_Amount.setText(rs.getString("amount"));
              txt_Cgst.setText(rs.getString("cgst"));
              txt_sgst.setText(rs.getString("sgst"));
              txt_total.setText(rs.getString("total_amount"));
             Total_In_Words.setText(rs.getString("total_in_words"));
               txt_Reamark.setText(rs.getString("remark"));
               txt_course_name.setText(rs.getString("course_name"));
             
            
        }
         catch(Exception e)
                     {
                     e.printStackTrace();
                     }
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        jlebelHome = new javax.swing.JLabel();
        jPanelSearchRecord = new javax.swing.JPanel();
        jLabelSearchReacord = new javax.swing.JLabel();
        jPanelEditCourse = new javax.swing.JPanel();
        jLabelEditCourse = new javax.swing.JLabel();
        jPanelCourseList = new javax.swing.JPanel();
        jLabelCourseList = new javax.swing.JLabel();
        jPanelViewAllRecord = new javax.swing.JPanel();
        jLabelViewAllRecord = new javax.swing.JLabel();
        jPanelBack = new javax.swing.JPanel();
        jLabelBack = new javax.swing.JLabel();
        jPanelLogout = new javax.swing.JPanel();
        jLabelLogout = new javax.swing.JLabel();
        jPanelPrint = new javax.swing.JPanel();
        jLabelPrint = new javax.swing.JLabel();
        jPanelPrint1 = new javax.swing.JPanel();
        jLabelPrint1 = new javax.swing.JLabel();
        jPanelEdit = new javax.swing.JPanel();
        jLabelEdit = new javax.swing.JLabel();
        print_reciept = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_GSTIN = new javax.swing.JLabel();
        Receiver_sig = new javax.swing.JLabel();
        txt_Payment_mode = new javax.swing.JLabel();
        txt_Cheque_dd_no = new javax.swing.JLabel();
        txt_bank_name = new javax.swing.JLabel();
        txt_Recieved_from = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_year2 = new javax.swing.JLabel();
        lbl_cheque_Dd = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txt_Receipt_no = new javax.swing.JLabel();
        Total_In_Words = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_course_name = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_Amount = new javax.swing.JLabel();
        txt_Cgst = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txt_sgst = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txt_Reamark = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txt_Date = new javax.swing.JLabel();
        txt_year1 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_total = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1560, 1050));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHome.setBackground(new java.awt.Color(0, 51, 51));
        panelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlebelHome.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jlebelHome.setForeground(new java.awt.Color(255, 255, 255));
        jlebelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managemeant_system3/images/home.png"))); // NOI18N
        jlebelHome.setText("      Home");
        jlebelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlebelHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlebelHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlebelHomeMouseExited(evt);
            }
        });
        panelHome.add(jlebelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, 60));

        jPanel1.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 270, 80));

        jPanelSearchRecord.setBackground(new java.awt.Color(0, 51, 51));
        jPanelSearchRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jPanelSearchRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSearchReacord.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jLabelSearchReacord.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSearchReacord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managemeant_system3/images/search2.png"))); // NOI18N
        jLabelSearchReacord.setText("Search Record");
        jLabelSearchReacord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSearchReacordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSearchReacordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSearchReacordMouseExited(evt);
            }
        });
        jPanelSearchRecord.add(jLabelSearchReacord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 70));

        jPanel1.add(jPanelSearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 270, 80));

        jPanelEditCourse.setBackground(new java.awt.Color(0, 51, 51));
        jPanelEditCourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jPanelEditCourse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEditCourse.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jLabelEditCourse.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEditCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managemeant_system3/images/edit2.png"))); // NOI18N
        jLabelEditCourse.setText("Edit Course");
        jLabelEditCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelEditCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelEditCourseMouseExited(evt);
            }
        });
        jLabelEditCourse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabelEditCourseKeyPressed(evt);
            }
        });
        jPanelEditCourse.add(jLabelEditCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, 60));

        jPanel1.add(jPanelEditCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 270, 80));

        jPanelCourseList.setBackground(new java.awt.Color(0, 51, 51));
        jPanelCourseList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jPanelCourseList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCourseList.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jLabelCourseList.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCourseList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managemeant_system3/images/list.png"))); // NOI18N
        jLabelCourseList.setText("Course List");
        jLabelCourseList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCourseListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCourseListMouseExited(evt);
            }
        });
        jPanelCourseList.add(jLabelCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 60));

        jPanel1.add(jPanelCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 270, 70));

        jPanelViewAllRecord.setBackground(new java.awt.Color(0, 51, 51));
        jPanelViewAllRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jPanelViewAllRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelViewAllRecord.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jLabelViewAllRecord.setForeground(new java.awt.Color(255, 255, 255));
        jLabelViewAllRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managemeant_system3/images/view all record.png"))); // NOI18N
        jLabelViewAllRecord.setText("View All Record");
        jLabelViewAllRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelViewAllRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelViewAllRecordMouseExited(evt);
            }
        });
        jPanelViewAllRecord.add(jLabelViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 260, 60));

        jPanel1.add(jPanelViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 270, 80));

        jPanelBack.setBackground(new java.awt.Color(0, 51, 51));
        jPanelBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jPanelBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBack.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jLabelBack.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managemeant_system3/images/left-arrow.png"))); // NOI18N
        jLabelBack.setText("     Back");
        jLabelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBackMouseExited(evt);
            }
        });
        jPanelBack.add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 60));

        jPanel1.add(jPanelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 270, 80));

        jPanelLogout.setBackground(new java.awt.Color(0, 51, 51));
        jPanelLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jPanelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelLogoutMouseEntered(evt);
            }
        });
        jPanelLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogout.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabelLogout.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managemeant_system3/images/logout.png"))); // NOI18N
        jLabelLogout.setText("LogOut");
        jLabelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelLogoutMouseExited(evt);
            }
        });
        jPanelLogout.add(jLabelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 60));

        jPanel1.add(jPanelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 270, 80));

        jPanelPrint.setBackground(new java.awt.Color(0, 51, 51));
        jPanelPrint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jPanelPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelPrintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelPrintMouseExited(evt);
            }
        });
        jPanelPrint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPrint.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabelPrint.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managemeant_system3/images/printer-.png"))); // NOI18N
        jLabelPrint.setText("   Print");
        jLabelPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPrintMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelPrintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelPrintMouseExited(evt);
            }
        });
        jPanelPrint.add(jLabelPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 60));

        jPanelPrint1.setBackground(new java.awt.Color(0, 51, 51));
        jPanelPrint1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jPanelPrint1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelPrint1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelPrint1MouseExited(evt);
            }
        });
        jPanelPrint1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPrint1.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabelPrint1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrint1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managemeant_system3/images/printer-.png"))); // NOI18N
        jLabelPrint1.setText("   Print");
        jLabelPrint1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelPrint1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelPrint1MouseExited(evt);
            }
        });
        jPanelPrint1.add(jLabelPrint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 60));

        jPanelPrint.add(jPanelPrint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 270, 80));

        jPanel1.add(jPanelPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 270, 80));

        jPanelEdit.setBackground(new java.awt.Color(0, 51, 51));
        jPanelEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, null, null));
        jPanelEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEdit.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabelEdit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managemeant_system3/images/edit2.png"))); // NOI18N
        jLabelEdit.setText("     Edit");
        jLabelEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelEditMouseExited(evt);
            }
        });
        jPanelEdit.add(jLabelEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 60));

        jPanel1.add(jPanelEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 780, 270, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 990));

        print_reciept.setBackground(new java.awt.Color(255, 255, 255));
        print_reciept.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 102));
        jLabel10.setText("ROORKEE INSTITUTE OF TECHNOLOGY");
        print_reciept.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 470, 70));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 102));
        jLabel12.setText("RIT , Nack A++ GRADE,Uttrakhand,IT Sector");
        print_reciept.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 430, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 102));
        jLabel11.setText("Puhana,Roorkee(247667),Uttrakhand");
        print_reciept.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 350, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managemeant_system3/images/th.jpeg"))); // NOI18N
        print_reciept.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 190));

        jPanel3.setBackground(new java.awt.Color(51, 0, 102));
        print_reciept.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1210, -1));

        txt_GSTIN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_GSTIN.setForeground(new java.awt.Color(0, 0, 102));
        txt_GSTIN.setText("GSTIN :");
        print_reciept.add(txt_GSTIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 290, 130, 30));

        Receiver_sig.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Receiver_sig.setForeground(new java.awt.Color(0, 0, 102));
        Receiver_sig.setText("Receiver Signature");
        print_reciept.add(Receiver_sig, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 730, 150, 30));

        txt_Payment_mode.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_Payment_mode.setForeground(new java.awt.Color(0, 0, 102));
        txt_Payment_mode.setText("Payment Mode :");
        print_reciept.add(txt_Payment_mode, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 130, 30));

        txt_Cheque_dd_no.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_Cheque_dd_no.setForeground(new java.awt.Color(0, 0, 102));
        txt_Cheque_dd_no.setText("Cheque_dd no:");
        print_reciept.add(txt_Cheque_dd_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 150, 30));

        txt_bank_name.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_bank_name.setForeground(new java.awt.Color(0, 0, 102));
        txt_bank_name.setText("Bank Name :");
        print_reciept.add(txt_bank_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 100, 30));

        txt_Recieved_from.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_Recieved_from.setForeground(new java.awt.Color(0, 0, 102));
        txt_Recieved_from.setText("Recieved From :");
        print_reciept.add(txt_Recieved_from, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 120, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("The following Payment in the college office for the Year :");
        print_reciept.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 420, 30));

        txt_year2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_year2.setForeground(new java.awt.Color(0, 0, 102));
        txt_year2.setText("2024");
        print_reciept.add(txt_year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 50, 30));

        lbl_cheque_Dd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_cheque_Dd.setForeground(new java.awt.Color(0, 0, 102));
        lbl_cheque_Dd.setText("Cheque_dd no :");
        print_reciept.add(lbl_cheque_Dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 150, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 51, 102));
        print_reciept.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 1190, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 51, 102));
        print_reciept.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 1190, 10));

        txt_Receipt_no.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_Receipt_no.setForeground(new java.awt.Color(0, 0, 102));
        txt_Receipt_no.setText("Receipt no :   RIT-");
        print_reciept.add(txt_Receipt_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 140, 30));

        Total_In_Words.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Total_In_Words.setForeground(new java.awt.Color(0, 0, 102));
        Total_In_Words.setText("Total In words");
        print_reciept.add(Total_In_Words, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 640, 530, 30));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("Head");
        print_reciept.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 50, 30));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setText("Sr. no");
        print_reciept.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 150, 30));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setText("1");
        print_reciept.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 40, 30));

        txt_course_name.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_course_name.setForeground(new java.awt.Color(0, 0, 102));
        txt_course_name.setText("1");
        print_reciept.add(txt_course_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 70, 30));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 102));
        jLabel20.setText("CGST (9 % )");
        print_reciept.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 150, 30));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 102));
        jLabel21.setText("Amount(Rs)");
        print_reciept.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 470, 150, 30));

        txt_Amount.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_Amount.setForeground(new java.awt.Color(0, 0, 102));
        txt_Amount.setText("Amount(Rs)");
        print_reciept.add(txt_Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 510, 150, 30));

        txt_Cgst.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_Cgst.setForeground(new java.awt.Color(0, 0, 102));
        txt_Cgst.setText("CGST");
        print_reciept.add(txt_Cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 540, 150, 30));
        print_reciept.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 650, 280, 10));

        txt_sgst.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_sgst.setForeground(new java.awt.Color(0, 0, 102));
        txt_sgst.setText("SGST");
        print_reciept.add(txt_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 570, 150, 30));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 102));
        jLabel25.setText("SGST (9 %)");
        print_reciept.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, 150, 30));

        txt_Reamark.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_Reamark.setForeground(new java.awt.Color(0, 0, 102));
        txt_Reamark.setText("Remark:");
        print_reciept.add(txt_Reamark, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 690, 310, 60));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 102));
        print_reciept.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 600, 280, 10));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("Payment Mode :");
        print_reciept.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 120, 30));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 102));
        jLabel28.setText("Bank Name :");
        print_reciept.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 100, 30));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 102));
        jLabel29.setText("Recieved From :");
        print_reciept.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 120, 30));

        txt_Date.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_Date.setForeground(new java.awt.Color(0, 0, 102));
        txt_Date.setText("Date :");
        print_reciept.add(txt_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 240, 140, 30));

        txt_year1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_year1.setForeground(new java.awt.Color(0, 0, 102));
        txt_year1.setText("2023");
        print_reciept.add(txt_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 50, 30));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel32.setText("-");
        print_reciept.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 20, 30));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 102));
        jLabel33.setText("Date :");
        print_reciept.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, 50, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("GSTIN :");
        print_reciept.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, 70, 30));

        txt_total.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_total.setForeground(new java.awt.Color(0, 0, 102));
        txt_total.setText("Total");
        print_reciept.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 610, 150, 30));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 102));
        jLabel30.setText("Total in Words:");
        print_reciept.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 150, 30));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 102));
        jLabel34.setText("Remark:");
        print_reciept.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 700, 70, 30));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 102));
        jLabel35.setText("Receipt no :   RIT-");
        print_reciept.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 140, 30));

        getContentPane().add(print_reciept, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 1050, 920));

        jLabel27.setFont(new java.awt.Font("Palatino Linotype", 1, 55)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Print  Receipt");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 370, 90));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jlebelHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlebelHomeMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(0,153,153);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_jlebelHomeMouseEntered

    private void jlebelHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlebelHomeMouseExited
        // TODO add your handling code here:
        Color clr=new Color(0,51,51);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_jlebelHomeMouseExited

    private void jLabelSearchReacordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchReacordMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(0,153,153);
        jPanelSearchRecord.setBackground(clr);
    }//GEN-LAST:event_jLabelSearchReacordMouseEntered

    private void jLabelSearchReacordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchReacordMouseExited
        // TODO add your handling code here:
        Color clr=new Color(0,51,51);
        jPanelSearchRecord.setBackground(clr);
    }//GEN-LAST:event_jLabelSearchReacordMouseExited

    private void jLabelEditCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEditCourseMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(0,153,153);
        jPanelEditCourse.setBackground(clr);
    }//GEN-LAST:event_jLabelEditCourseMouseEntered

    private void jLabelEditCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEditCourseMouseExited
        // TODO add your handling code here:
        Color clr=new Color(0,51,51);
        jPanelEditCourse.setBackground(clr);
    }//GEN-LAST:event_jLabelEditCourseMouseExited

    private void jLabelEditCourseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelEditCourseKeyPressed
        // TODO add your handling code here:
        //         Color clr=new Color(0,153,153);
        //        jPanelEditCourse.setBackground(clr);
    }//GEN-LAST:event_jLabelEditCourseKeyPressed

    private void jLabelCourseListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCourseListMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(0,153,153);
        jPanelCourseList.setBackground(clr);
    }//GEN-LAST:event_jLabelCourseListMouseEntered

    private void jLabelCourseListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCourseListMouseExited
        // TODO add your handling code here:
        Color clr=new Color(0,51,51);
        jPanelCourseList.setBackground(clr);
    }//GEN-LAST:event_jLabelCourseListMouseExited

    private void jLabelViewAllRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelViewAllRecordMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(0,153,153);
        jPanelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_jLabelViewAllRecordMouseEntered

    private void jLabelViewAllRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelViewAllRecordMouseExited
        // TODO add your handling code here:
        Color clr=new Color(0,51,51);
        jPanelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_jLabelViewAllRecordMouseExited

    private void jLabelBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(0,153,153);
        jPanelBack.setBackground(clr);
    }//GEN-LAST:event_jLabelBackMouseEntered

    private void jLabelBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseExited
        // TODO add your handling code here:
        Color clr=new Color(0,51,51);
        jPanelBack.setBackground(clr);
    }//GEN-LAST:event_jLabelBackMouseExited

    private void jLabelLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoutMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(0,153,153);
        jPanelLogout.setBackground(clr);

    }//GEN-LAST:event_jLabelLogoutMouseEntered

    private void jLabelLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoutMouseExited
        // TODO add your handling code here:
        Color clr=new Color(0,51,51);
        jPanelLogout.setBackground(clr);
    }//GEN-LAST:event_jLabelLogoutMouseExited

    private void jLabelPrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPrintMouseEntered
        // TODO add your handling code here:
         Color clr=new Color(0,153,153);
       jPanelPrint.setBackground(clr);
    }//GEN-LAST:event_jLabelPrintMouseEntered

    private void jLabelPrintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPrintMouseExited
        // TODO add your handling code here:
         Color clr=new Color(0,51,51);
     jPanelPrint.setBackground(clr);
        
    }//GEN-LAST:event_jLabelPrintMouseExited

    private void jPanelPrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPrintMouseEntered
        // TODO add your handling code here:
         Color clr=new Color(0,153,153);
        jPanelPrint.setBackground(clr);
        
        
    }//GEN-LAST:event_jPanelPrintMouseEntered

    private void jPanelPrintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPrintMouseExited
        // TODO add your handling code here:
         Color clr=new Color(0,51,51);
        jPanelPrint.setBackground(clr);
    }//GEN-LAST:event_jPanelPrintMouseExited

    private void jPanelLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLogoutMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelLogoutMouseEntered

    private void jLabelPrint1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPrint1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelPrint1MouseEntered

    private void jLabelPrint1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPrint1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelPrint1MouseExited

    private void jPanelPrint1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPrint1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelPrint1MouseEntered

    private void jPanelPrint1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPrint1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelPrint1MouseExited

    private void jLabelPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPrintMouseClicked
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                print_reciept.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
    }//GEN-LAST:event_jLabelPrintMouseClicked

    private void jLabelEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEditMouseEntered
        // TODO add your handling code here:
         Color clr=new Color(0,153,153);
        jPanelEdit.setBackground(clr);
    }//GEN-LAST:event_jLabelEditMouseEntered

    private void jLabelEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEditMouseExited
        // TODO add your handling code here:
        Color clr=new Color(0,51,51);
     jPanelEdit.setBackground(clr); 
        
    }//GEN-LAST:event_jLabelEditMouseExited

    private void jLabelEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEditMouseClicked
        // TODO add your handling code here:
        updateDetails up=new updateDetails();
        up.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jLabelEditMouseClicked

    private void jlebelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlebelHomeMouseClicked
        // TODO add your handling code here:
         home h=new home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlebelHomeMouseClicked

    private void jLabelSearchReacordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchReacordMouseClicked
        // TODO add your handling code here:
        SearchRecord sr=new SearchRecord();
        sr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelSearchReacordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintRecipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintRecipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintRecipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintRecipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintRecipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Receiver_sig;
    private javax.swing.JLabel Total_In_Words;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelCourseList;
    private javax.swing.JLabel jLabelEdit;
    private javax.swing.JLabel jLabelEditCourse;
    private javax.swing.JLabel jLabelLogout;
    private javax.swing.JLabel jLabelPrint;
    private javax.swing.JLabel jLabelPrint1;
    private javax.swing.JLabel jLabelSearchReacord;
    private javax.swing.JLabel jLabelViewAllRecord;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelBack;
    private javax.swing.JPanel jPanelCourseList;
    private javax.swing.JPanel jPanelEdit;
    private javax.swing.JPanel jPanelEditCourse;
    private javax.swing.JPanel jPanelLogout;
    private javax.swing.JPanel jPanelPrint;
    private javax.swing.JPanel jPanelPrint1;
    private javax.swing.JPanel jPanelSearchRecord;
    private javax.swing.JPanel jPanelViewAllRecord;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel jlebelHome;
    private javax.swing.JLabel lbl_cheque_Dd;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel print_reciept;
    private javax.swing.JLabel txt_Amount;
    private javax.swing.JLabel txt_Cgst;
    private javax.swing.JLabel txt_Cheque_dd_no;
    private javax.swing.JLabel txt_Date;
    private javax.swing.JLabel txt_GSTIN;
    private javax.swing.JLabel txt_Payment_mode;
    private javax.swing.JLabel txt_Reamark;
    private javax.swing.JLabel txt_Receipt_no;
    private javax.swing.JLabel txt_Recieved_from;
    private javax.swing.JLabel txt_bank_name;
    private javax.swing.JLabel txt_course_name;
    private javax.swing.JLabel txt_sgst;
    private javax.swing.JLabel txt_total;
    private javax.swing.JLabel txt_year1;
    private javax.swing.JLabel txt_year2;
    // End of variables declaration//GEN-END:variables
}
