/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package fees_managemeant_system3;
import java.util.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Niwash Kumar
 */
public class SearchRecord extends javax.swing.JFrame {

    /**
     * Creates new form SearchRecord
     */
    DefaultTableModel model;
    public SearchRecord() {
        initComponents();
        setRecordTable();
    }
    public void setRecordTable(){
        try{
            Connection con= DBConnection.getConnection();
            PreparedStatement pst=con.prepareStatement("select* from fees_Details ");
             java.sql.ResultSet rs=pst.executeQuery();
            // rs.next();
            while(rs.next()){
                String Receipt=rs.getString("reciept_no");
                String Roll_no=rs.getString("roll_no");
                String Student_name=rs.getString("student_name"); 
                String course_name=rs.getString("course_name");
                String payment_mode=rs.getString("payment_mode");
                Float Amount=rs.getFloat("total_amount");
                 String Remark=rs.getString("remark");
                 
                 
                 Object[] obj={ Receipt,Roll_no,Student_name,course_name,payment_mode, Amount,Remark};
                 model=(DefaultTableModel)tbl_studentData.getModel();
                 model.addRow(obj);
                 
                
                
            }
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
        
    }
    
    public void Search(String str){
        model=(DefaultTableModel)tbl_studentData.getModel();
        TableRowSorter<DefaultTableModel> trs=new TableRowSorter<>(model);
      tbl_studentData.setRowSorter (trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        jlebelHome = new javax.swing.JLabel();
        jPanelSearchRecord = new javax.swing.JPanel();
        jLabelSearchReacord = new javax.swing.JLabel();
        jPanelEditCourse = new javax.swing.JPanel();
        jLabelEditCourse = new javax.swing.JLabel();
        jPanelCourseList = new javax.swing.JPanel();
        jLabelCourseList = new javax.swing.JLabel();
        jPanelViewAllRecord = new javax.swing.JPanel();
        jLabelViewAllRecord = new javax.swing.JLabel();
        jPanelBack = new javax.swing.JPanel();
        jLabelBack = new javax.swing.JLabel();
        jPanelLogout = new javax.swing.JPanel();
        jLabelLogout = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_studentData = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Searching_table = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHome.setBackground(new java.awt.Color(0, 51, 51));
        panelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlebelHome.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jlebelHome.setForeground(new java.awt.Color(255, 255, 255));
        jlebelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managemeant_system3/images/home.png"))); // NOI18N
        jlebelHome.setText("      Home");
        jlebelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlebelHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlebelHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlebelHomeMouseExited(evt);
            }
        });
        panelHome.add(jlebelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, 60));

        jPanel1.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 270, 80));

        jPanelSearchRecord.setBackground(new java.awt.Color(0, 51, 51));
        jPanelSearchRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jPanelSearchRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSearchReacord.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jLabelSearchReacord.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSearchReacord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managemeant_system3/images/search2.png"))); // NOI18N
        jLabelSearchReacord.setText("Search Record");
        jLabelSearchReacord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSearchReacordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSearchReacordMouseExited(evt);
            }
        });
        jPanelSearchRecord.add(jLabelSearchReacord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 70));

        jPanel1.add(jPanelSearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 270, 80));

        jPanelEditCourse.setBackground(new java.awt.Color(0, 51, 51));
        jPanelEditCourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jPanelEditCourse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEditCourse.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jLabelEditCourse.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEditCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managemeant_system3/images/edit2.png"))); // NOI18N
        jLabelEditCourse.setText("Edit Course");
        jLabelEditCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEditCourseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelEditCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelEditCourseMouseExited(evt);
            }
        });
        jLabelEditCourse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabelEditCourseKeyPressed(evt);
            }
        });
        jPanelEditCourse.add(jLabelEditCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, 60));

        jPanel1.add(jPanelEditCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 270, 80));

        jPanelCourseList.setBackground(new java.awt.Color(0, 51, 51));
        jPanelCourseList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jPanelCourseList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCourseList.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jLabelCourseList.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCourseList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managemeant_system3/images/list.png"))); // NOI18N
        jLabelCourseList.setText("Course List");
        jLabelCourseList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCourseListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCourseListMouseExited(evt);
            }
        });
        jPanelCourseList.add(jLabelCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 60));

        jPanel1.add(jPanelCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 270, 70));

        jPanelViewAllRecord.setBackground(new java.awt.Color(0, 51, 51));
        jPanelViewAllRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jPanelViewAllRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelViewAllRecord.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jLabelViewAllRecord.setForeground(new java.awt.Color(255, 255, 255));
        jLabelViewAllRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managemeant_system3/images/view all record.png"))); // NOI18N
        jLabelViewAllRecord.setText("View All Record");
        jLabelViewAllRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelViewAllRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelViewAllRecordMouseExited(evt);
            }
        });
        jPanelViewAllRecord.add(jLabelViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 260, 60));

        jPanel1.add(jPanelViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 270, 80));

        jPanelBack.setBackground(new java.awt.Color(0, 51, 51));
        jPanelBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jPanelBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBack.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jLabelBack.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managemeant_system3/images/left-arrow.png"))); // NOI18N
        jLabelBack.setText("     Back");
        jLabelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBackMouseExited(evt);
            }
        });
        jPanelBack.add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 60));

        jPanel1.add(jPanelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 270, 80));

        jPanelLogout.setBackground(new java.awt.Color(0, 51, 51));
        jPanelLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jPanelLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogout.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabelLogout.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_managemeant_system3/images/logout.png"))); // NOI18N
        jLabelLogout.setText("       Logout");
        jLabelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelLogoutMouseExited(evt);
            }
        });
        jPanelLogout.add(jLabelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, 60));

        jPanel1.add(jPanelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 630, 270, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 1080));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_studentData.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        tbl_studentData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Receipt No.", "Roll No.", "Student Name.", "Course Name", "Payment Mode.", "Amount.", "Remark"
            }
        ));
        jScrollPane2.setViewportView(tbl_studentData);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 950, 640));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Search Name:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 190, 30));

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search Record");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 190, 30));

        Searching_table.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Searching_table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Searching_tableKeyReleased(evt);
            }
        });
        jPanel2.add(Searching_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 270, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 1030, 1080));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jlebelHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlebelHomeMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(0,153,153);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_jlebelHomeMouseEntered

    private void jlebelHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlebelHomeMouseExited
        // TODO add your handling code here:
        Color clr=new Color(0,51,51);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_jlebelHomeMouseExited

    private void jLabelSearchReacordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchReacordMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(0,153,153);
        jPanelSearchRecord.setBackground(clr);
    }//GEN-LAST:event_jLabelSearchReacordMouseEntered

    private void jLabelSearchReacordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchReacordMouseExited
        // TODO add your handling code here:
        Color clr=new Color(0,51,51);
        jPanelSearchRecord.setBackground(clr);
    }//GEN-LAST:event_jLabelSearchReacordMouseExited

    private void jLabelEditCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEditCourseMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(0,153,153);
        jPanelEditCourse.setBackground(clr);
    }//GEN-LAST:event_jLabelEditCourseMouseEntered

    private void jLabelEditCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEditCourseMouseExited
        // TODO add your handling code here:
        Color clr=new Color(0,51,51);
        jPanelEditCourse.setBackground(clr);
    }//GEN-LAST:event_jLabelEditCourseMouseExited

    private void jLabelEditCourseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelEditCourseKeyPressed
        // TODO add your handling code here:
        //         Color clr=new Color(0,153,153);
        //        jPanelEditCourse.setBackground(clr);
    }//GEN-LAST:event_jLabelEditCourseKeyPressed

    private void jLabelCourseListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCourseListMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(0,153,153);
        jPanelCourseList.setBackground(clr);
    }//GEN-LAST:event_jLabelCourseListMouseEntered

    private void jLabelCourseListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCourseListMouseExited
        // TODO add your handling code here:
        Color clr=new Color(0,51,51);
        jPanelCourseList.setBackground(clr);
    }//GEN-LAST:event_jLabelCourseListMouseExited

    private void jLabelViewAllRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelViewAllRecordMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(0,153,153);
        jPanelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_jLabelViewAllRecordMouseEntered

    private void jLabelViewAllRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelViewAllRecordMouseExited
        // TODO add your handling code here:
        Color clr=new Color(0,51,51);
        jPanelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_jLabelViewAllRecordMouseExited

    private void jLabelBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(0,153,153);
        jPanelBack.setBackground(clr);
    }//GEN-LAST:event_jLabelBackMouseEntered

    private void jLabelBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseExited
        // TODO add your handling code here:
        Color clr=new Color(0,51,51);
        jPanelBack.setBackground(clr);
    }//GEN-LAST:event_jLabelBackMouseExited

    private void jLabelLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoutMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(0,153,153);
        jPanelLogout.setBackground(clr);

    }//GEN-LAST:event_jLabelLogoutMouseEntered

    private void jLabelLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoutMouseExited
        // TODO add your handling code here:
        Color clr=new Color(0,51,51);
        jPanelLogout.setBackground(clr);
    }//GEN-LAST:event_jLabelLogoutMouseExited

    private void Searching_tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Searching_tableKeyReleased
        // TODO add your handling code here:
        String SearchString=Searching_table.getText();
        Search(SearchString);
    }//GEN-LAST:event_Searching_tableKeyReleased

    private void jlebelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlebelHomeMouseClicked
        // TODO add your handling code here:
         home h=new home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlebelHomeMouseClicked

    private void jLabelEditCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEditCourseMouseClicked
        // TODO add your handling code here:
        EditCourse ed=new EditCourse();
        ed.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelEditCourseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Searching_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelCourseList;
    private javax.swing.JLabel jLabelEditCourse;
    private javax.swing.JLabel jLabelLogout;
    private javax.swing.JLabel jLabelSearchReacord;
    private javax.swing.JLabel jLabelViewAllRecord;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBack;
    private javax.swing.JPanel jPanelCourseList;
    private javax.swing.JPanel jPanelEditCourse;
    private javax.swing.JPanel jPanelLogout;
    private javax.swing.JPanel jPanelSearchRecord;
    private javax.swing.JPanel jPanelViewAllRecord;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlebelHome;
    private javax.swing.JPanel panelHome;
    private javax.swing.JTable tbl_studentData;
    // End of variables declaration//GEN-END:variables
}
